gdoc/Controllers/DocumentoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using gdoc.Models;
using System.IO;
using PagedList;
namespace gdoc.Controllers
{
    public class DocumentoController : Controller
    {
        private ModeloDados db = new ModeloDados();

        // GET: Documento
        [Authorize]
        public ActionResult index(int? page)
        {
            IQueryable<Documento> documentos = db.Documento;
            IPagedList<Documento> documentoPaged = documentos.OrderBy(x => x.dataCadastro).ToPagedList(page ?? 1, 10);
            IPagedList<Documento> model = documentos.OrderBy(x => x.dataCadastro).ToPagedList(page ?? 1, 10);
            return View(model);

            
        }

        // GET: Documento/Details/5
        [Authorize]
        public ActionResult detalhe(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Documento documento = db.Documento.Find(id);
            if (documento == null)
            {
                return HttpNotFound();
            }
            return View(documento);
        }

        // GET: Documento/Create
        [Authorize]
        public ActionResult criar()
        {
            return View();
        }

        // POST: Documento/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult criar([Bind(Include = "idDocumento,nomeDocumento,tipoDocumento,observacaoDocumento,dataCadastro,nomeArquivo")] Documento documento)
        {
 

        
            try
                {
                
                    HttpPostedFileBase file = Request.Files[0];



                    string nomeArquivoSalvar = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "arquivos");

                    nomeArquivoSalvar = Path.Combine(nomeArquivoSalvar, Path.GetFileName(file.FileName));

                    file.SaveAs(nomeArquivoSalvar);

                    documento.nomeDocumento = Request.Form["nomeDocumento"];

                    documento.tipoDocumento = Request.Form["tipoDocumento"];
                    documento.observacaoDocumento = Request.Form["observacaoDocumento"];
                
                    documento.nomeArquivo = file.FileName;

                

                    db.Documento.Add(documento);
                    db.SaveChanges();
                    return RedirectToAction("index");
                
            }
                catch(Exception e)
                {
                
                Response.Write("Erro: " + e.Message);
                Response.End();
                }
               
           

            return View(documento);
        }

        // GET: Documento/Edit/5
        [Authorize]
        public ActionResult editar(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Documento documento = db.Documento.Find(id);
            if (documento == null)
            {
                return HttpNotFound();
            }
            return View(documento);
        }

        // POST: Documento/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult editar([Bind(Include = "idDocumento,nomeDocumento,tipoDocumento,observacaoDocumento,dataCadastro,nomeArquivo")] Documento documento)
        {


            try
            {

                HttpPostedFileBase file = Request.Files[0];


                /* Excluo o arquivo pra depois subir outro */
                if (file.ContentLength > 0)
                {

                    System.IO.File.Delete(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "arquivos\\" + documento.nomeArquivo));

                    string nomeArquivoSalvar = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "arquivos");

                    nomeArquivoSalvar = Path.Combine(nomeArquivoSalvar, Path.GetFileName(file.FileName));

                    file.SaveAs(nomeArquivoSalvar);

                }

                documento.nomeDocumento = Request.Form["nomeDocumento"];

                documento.tipoDocumento = Request.Form["tipoDocumento"];
                documento.observacaoDocumento = Request.Form["observacaoDocumento"];

                documento.nomeArquivo = file.FileName;


                db.Entry(documento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("index");


            }
            catch(Exception e)
            {

                Response.Write("Erro: " + e.Message);
                Response.End();

            }
         
            return View(documento);
        }

        // GET: Documento/Delete/5
        [Authorize]
        public ActionResult excluir(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Documento documento = db.Documento.Find(id);
            if (documento == null)
            {
                return HttpNotFound();
            }
            return View(documento);
        }

        // POST: Documento/Delete/5
        [HttpPost, ActionName("excluir")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(long id)
        {
            Documento documento = db.Documento.Find(id);
                try
                {
                    System.IO.File.Delete(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "arquivos\\" + documento.nomeArquivo));
                    db.Documento.Remove(documento);
                    db.SaveChanges();
                    return RedirectToAction("index");

                }
                catch(Exception e)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError); 

                }
     
            return RedirectToAction("index");

        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

gdoc/Views/Documento/Create.cshtml
@model gdoc.Models.Documento

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Documento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NomeDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeDocumento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeDocumento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescricaoDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescricaoDocumento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescricaoDocumento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataDocumento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataDocumento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataCadastroDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataCadastroDocumento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataCadastroDocumento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdTipoDocumento, "IdTipoDocumento", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdTipoDocumento", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTipoDocumento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

gdoc/Views/Documento/Delete.cshtml
@model gdoc.Models.Documento

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Documento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescricaoDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescricaoDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCadastroDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCadastroDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoDocumento.DescricaoTipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoDocumento.DescricaoTipo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

gdoc/Views/Documento/Details.cshtml
@model gdoc.Models.Documento

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Documento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescricaoDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescricaoDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCadastroDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCadastroDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoDocumento.DescricaoTipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoDocumento.DescricaoTipo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

gdoc/Views/Documento/Edit.cshtml
@model gdoc.Models.Documento

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Documento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.NomeDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeDocumento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeDocumento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescricaoDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescricaoDocumento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescricaoDocumento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataDocumento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataDocumento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataCadastroDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataCadastroDocumento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataCadastroDocumento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdTipoDocumento, "IdTipoDocumento", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdTipoDocumento", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTipoDocumento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

gdoc/Views/Documento/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<gdoc.Models.Documento>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Documentos Cadastrados</h2>

<p>
    @Html.ActionLink("Cadastrar Novo Documento", "criar")
</p>
<table class="table">
<thead>
    <tr>
        <th>
            Documento
        </th>
        <th>
            Tipo de documento
        </th>
        <th>
            Observação
        </th>
        <th>
            Data de cadastro
        </th>
        <th>
            Ações
        </th>
    </tr>
</thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nomeDocumento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tipoDocumento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.observacaoDocumento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dataCadastro)
                </td>
                <td>
                    @Html.ActionLink("Alterar", "editar", new { id = item.idDocumento }) |
                    @Html.ActionLink("Detalhes", "detalhe", new { id = item.idDocumento }) |
                    @Html.ActionLink("Excluir", "excluir", new { id = item.idDocumento })
                </td>
            </tr>
        }
    </tbody>
</table>
@if (Model.HasNextPage || Model.HasPreviousPage)
{
    <div style="text-align: center">
        @Html.PagedListPager(Model, (page) => Url.Action("Index", new { page = page, filtro = @ViewBag.filtro }), PagedListRenderOptions.Classic)
    </div>
}

gdoc/Views/Documento/criar.cshtml
@model gdoc.Models.Documento

@{
    ViewBag.Title = "GDOC - Cadastrar novo Documento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@using (Html.BeginForm("criar", "Documento", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cadastrar novo documento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nomeDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomeDocumento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomeDocumento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">
                Arquivo:
            </label>
            <div class="col-md-10">
                <input type="file" name="arquivo" id="arquivo" required />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tipoDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.ValidationMessageFor(model => model.tipoDocumento, "", new { @class = "text-danger" })
                <select name="tipoDocumento" id="tipoDocumento" class="form-control">
                    <option value=""></option>
                    <option value="1">Conta</option>
                    <option value="2">Cheque</option>
                    <option value="3">Recibo</option>
                    <option value="4">Comprovante de Pagamento</option>
                    <option value="5">Foto</option>
                    <option value="6">Contracheque</option>
                    <option value="7">Nota fiscal</option>
                    <option value="8">Rifa</option>
                    <option value="9">Canhoto</option>
                    <option value="10">Bilhete de cinema</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.observacaoDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.observacaoDocumento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.observacaoDocumento, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Documentos Cadastrados", "index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

gdoc/Views/Documento/detalhe.cshtml
@model gdoc.Models.Documento

@{
    ViewBag.Title = "GDOC - Detalhes do Documento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes</h2>

<div>
    <h4>Documento</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.nomeArquivo)
        </dt>

        <dd>
            <span class="label label-info">
                <b>
                <a target="_blank" href="~/arquivos/@Html.DisplayFor(model => model.nomeArquivo)">@Html.DisplayFor(model => model.nomeArquivo)</a>
                </b>
            </span> 
</dd>


        <dt>
            @Html.DisplayNameFor(model => model.nomeDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomeDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipoDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipoDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.observacaoDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.observacaoDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dataCadastro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dataCadastro)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Alterar", "Edit", new { id = Model.idDocumento }) |
    @Html.ActionLink("Documentos Cadastrados", "index")
</p>

gdoc/Views/Documento/detalhes.cshtml
@model gdoc.Models.Documento

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes</h2>

<div>
    <h4>Documento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nomeDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomeDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipoDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipoDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.observacaoDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.observacaoDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dataCadastro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dataCadastro)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Alterar", "Edit", new { id = Model.idDocumento }) |
    @Html.ActionLink("Documentos Cadastrados", "index")
</p>

gdoc/Views/Documento/editar.cshtml
@model gdoc.Models.Documento

@{
    ViewBag.Title = "GDOC - Editar documento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Editar documento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idDocumento)

        <div class="form-group">
            @Html.LabelFor(model => model.nomeDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomeDocumento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomeDocumento, "", new { @class = "text-danger" })
            </div>
        </div>
        


        <div class="form-group">
        

        <div class="col-md-10">
            <label class="control-label col-md-2">
                Arquivo Atual
            </label>
            <div class="col-md-10">
                <b>
                    <a target="_blank" href="~/arquivos/@Html.DisplayFor(model => model.nomeArquivo)">@Html.DisplayFor(model => model.nomeArquivo)</a>
                </b>
            </div>

        </div>

        <div class="form-group">
                    <label class="control-label col-md-2">
                        Arquivo:
                    </label>
                    <div class="col-md-10">
                        <input type="file" name="arquivo" id="arquivo" required />
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.tipoDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <select name="tipoDocumento" id="tipoDocumento" class="form-control">
                            <option value=""></option>
                            <option value="1"
                                    @if (Model.tipoDocumento == "1")
                                    {
                                        @Html.Raw("selected='selected'")
                                    }
                                    >Conta</option>
                            <option value="2"
                                    @if (Model.tipoDocumento == "2")
                                    {
                                       @Html.Raw("selected='selected'")
                                    }
                                    >Cheque</option>
                            <option value="3"
                                    @if (Model.tipoDocumento == "3")
                                    {
                                       @Html.Raw("selected='selected'")
                                    }
                                    >Recibo</option>
                            <option value="4"
                                    @if (Model.tipoDocumento == "4")
                                    {
                                       @Html.Raw("selected='selected'")
                                    }
                                    >Comprovante de Pagamento</option>
                            <option value="5" 
                                    @if (Model.tipoDocumento == "5")
                                    {
                                       @Html.Raw("selected='selected'")
                                    }
                                    >Foto</option>
                            <option value="6"
                                    @if (Model.tipoDocumento == "6")
                                    {
                                       @Html.Raw("selected='selected'")
                                    }
                                    >Contracheque</option>
                            <option value="7"
                                    @if (Model.tipoDocumento == "7")
                                    {
                                        @Html.Raw("selected='selected'")
                                    }
                                    >Nota fiscal</option>
                            <option value="8"
                                    @if (Model.tipoDocumento == "8")
                                    {
                                        @Html.Raw("selected='selected'")
                                    }
                                    >Rifa</option>
                            <option value="9"
                                    @if (Model.tipoDocumento == "9")
                                    {
                                       @Html.Raw("selected='selected'")
                                    }
                                    >Canhoto</option>
                            <option value="10"
                                    @if (Model.tipoDocumento == "10")
                                    {
                                       @Html.Raw("selected='selected'")
                                    }
                                    >Bilhete de cinema</option>
                        </select>
                        @Html.ValidationMessageFor(model => model.tipoDocumento, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.observacaoDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.observacaoDocumento, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.observacaoDocumento, "", new { @class = "text-danger" })
                    </div>
                </div>

              
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Alterar" class="btn btn-default" />
                    </div>
                </div>
        </div>
        }


        <div>
            @Html.ActionLink("Documentos Cadastrados", "index")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

gdoc/Views/Documento/excluir.cshtml
@model gdoc.Models.Documento

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Excluir</h2>

<h3>Deseja realmente excluir este documento?</h3>
<div>
    <h4>Documento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nomeDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomeDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipoDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipoDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.observacaoDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.observacaoDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dataCadastro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dataCadastro)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Documentos Cadastrados", "Index")
        </div>
    }
</div>